{
 "title": "advCache dashboard",
 "description": "AdvanceCache - HTTP cache / reverse proxy.",
 "tags": [
  "common",
  "golang",
  "highload"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pod",
    "label": "Pods",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\",pod=~\"$deployment-[0-9a-z]+-[0-9a-z]+\"}, pod)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created{namespace=~\"PROJECT_NAMESPACE\"},namespace)"
    }
   },
   {
    "name": "deployment",
    "label": "deployment",
    "query": {
     "query": "label_values(up{namespace=\"$namespace\"},deployment)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{pod=~\"$pod\"}, container)"
    }
   },
   {
    "name": "metric_prefix",
    "query": {
     "query": "label_values({namespace=\"$namespace\"},__name__)"
    }
   },
   { "name": "percentile", "label": "percentile", "query": "0.99,0.95,0.90,0.75,0.50" },
   {
    "name": "other_pods",
    "label": "other pods",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\",pod!~\"$deployment-[0-9a-z]+-[0-9a-z]+\"}, created_by_name)"
    }
   },
   {
    "name": "backend",
    "label": "backend",
    "query": {
     "query": "label_values(   {__name__=~\"adv_cache_upstream_backend_is_(healthy|sick|dead|buried)\"},   backend )"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RPS & hits & misses & errors & panics",
   "type": "timeseries",
   "description": "hits per second (looks like RPS)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(adv_cache_cache_hits{app_gitBranch=\"BRANCH-NAME\"})[1m]",
     "legendFormat": "hits"
    },
    {
     "expr": "rate(adv_cache_cache_misses{app_gitBranch=\"BRANCH-NAME\"})[1m]",
     "legendFormat": "miss"
    },
    {
     "expr": "rate(adv_cache_total{app_gitBranch=\"BRANCH-NAME\"})[1m]",
     "legendFormat": "RPS"
    },
    {
     "expr": "rate(adv_cache_proxies{app_gitBranch=\"BRANCH-NAME\"})[1m]",
     "legendFormat": "proxies"
    },
    {
     "expr": "rate(adv_cache_errors{app_gitBranch=\"BRANCH-NAME\"})[1m]",
     "legendFormat": "errors"
    },
    {
     "expr": "rate(adv_cache_panics{app_gitBranch=\"BRANCH-NAME\"})[1m]",
     "legendFormat": "panics"
    }
   ]
  },
  {
   "title": "AVG. duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg_over_time(adv_cache_avg_duration_ns{app_gitBranch=\"BRANCH-NAME\"}[1m])",
     "legendFormat": "dur - 1m"
    },
    {
     "expr": "adv_cache_avg_duration_ns{app_gitBranch=\"BRANCH-NAME\"}",
     "legendFormat": "dur - 1s"
    },
    {
     "expr": "avg_over_time(adv_cache_avg_duration_ns{app_gitBranch=\"BRANCH-NAME\"}[5m])",
     "legendFormat": "dur - 5m"
    },
    {
     "expr": "avg_over_time(adv_cache_avg_duration_ns{app_gitBranch=\"BRANCH-NAME\"}[15m])",
     "legendFormat": "dur - 15min"
    }
   ]
  },
  {
   "title": "Storage length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "adv_cache_cache_length{app_gitBranch=\"BRANCH-NAME\"}",
     "legendFormat": "len"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "adv_cache_cache_memory_usage{app_gitBranch=\"BRANCH-NAME\"}",
     "legendFormat": "Memory usage"
    },
    {
     "expr": "process_resident_memory_bytes{app_gitBranch=\"BRANCH-NAME\"}",
     "legendFormat": "Process memory usage"
    },
    {
     "expr": "process_resident_memory_bytes{app_gitBranch=\"BRANCH-NAME\"} - adv_cache_cache_memory_usage{app_gitBranch=\"BRANCH-NAME\"}",
     "legendFormat": "Overhead (logical - physical memory)"
    },
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$namespace\",container=\"$container\",pod=~\"$deployment.*\"}",
     "legendFormat": "Container memory usage"
    }
   ]
  },
  {
   "title": "Hit rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * rate(adv_cache_cache_hits[30m]) / (rate(adv_cache_cache_hits[30m]) + rate(adv_cache_cache_misses[30m]))",
     "legendFormat": "Hit rate (%) - 30min"
    },
    {
     "expr": "100 * rate(adv_cache_cache_hits[15m]) / (rate(adv_cache_cache_hits[15m]) + rate(adv_cache_cache_misses[15m]))",
     "legendFormat": "Hit rate (%) - 15min"
    },
    {
     "expr": "100 * rate(adv_cache_cache_hits[5m]) / (rate(adv_cache_cache_hits[5m]) + rate(adv_cache_cache_misses[5m]))",
     "legendFormat": "Hit rate (%) - 5min"
    },
    {
     "expr": "100 * rate(adv_cache_cache_hits[1m]) / (rate(adv_cache_cache_hits[1m]) + rate(adv_cache_cache_misses[1m]))",
     "legendFormat": "Hit rate (%) - 1min"
    },
    {
     "expr": "100 * rate(adv_cache_cache_hits[30s]) / (rate(adv_cache_cache_hits[30s]) + rate(adv_cache_cache_misses[30s]))",
     "legendFormat": "Hit rate (%) - 30sec"
    },
    {
     "expr": "100 * rate(adv_cache_cache_hits[15s]) / (rate(adv_cache_cache_hits[15s]) + rate(adv_cache_cache_misses[15s]))",
     "legendFormat": "Hit rate (%) - 15sec"
    }
   ]
  },
  {
   "title": "Eviction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(adv_cache_soft_evicted_total_items{app_gitBranch=\"BRANCH-NAME\"})[15s]",
     "legendFormat": "soft: evicted"
    },
    {
     "expr": "rate(adv_cache_soft_evicted_total_bytes{app_gitBranch=\"BRANCH-NAME\"})[15s]",
     "legendFormat": "soft: bytes freed"
    },
    {
     "expr": "rate(adv_cache_soft_evicted_total_scans{app_gitBranch=\"BRANCH-NAME\"})[15s]",
     "legendFormat": "soft: scans"
    },
    {
     "expr": "rate(adv_cache_hard_evicted_total_items{app_gitBranch=\"BRANCH-NAME\"})[15s]",
     "legendFormat": "hard: evicted"
    },
    {
     "expr": "rate(adv_cache_hard_evicted_total_bytes{app_gitBranch=\"BRANCH-NAME\"})[15s]",
     "legendFormat": "hard: bytes freed"
    }
   ]
  },
  {
   "title": "Data refresher: scans, founds, attempts, refreshes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(adv_cache_refresh_updated[1m])",
     "legendFormat": "Updates"
    },
    {
     "expr": "rate(adv_cache_refresh_errors[1m])",
     "legendFormat": "Errors"
    },
    {
     "expr": "rate(adv_cache_refresh_scans[1m])",
     "legendFormat": "Scans"
    },
    {
     "expr": "rate(adv_cache_refresh_hits[1m])",
     "legendFormat": "Scan: hits"
    }
   ]
  },
  {
   "title": "Idle backends healthcheck probes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(adv_cache_upstream_backend_probes_success_total{backend=~\"$backend\"}[1m])",
     "legendFormat": "Success probe - {{backend}}"
    },
    {
     "expr": "rate(adv_cache_upstream_backend_probes_failed_total{backend=~\"$backend\"}[1m])",
     "legendFormat": "Failed probe - {{backend}}"
    }
   ]
  },
  {
   "title": "Cluster RPS & error rate per backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(adv_cache_upstream_backend_errors_total{backend=~\"$backend\"}[1m])",
     "legendFormat": "{{backend}} - err rate"
    },
    {
     "expr": "adv_cache_upstream_backend_current_rps{backend=~\"$backend\"}",
     "legendFormat": "{{backend}} - RPS"
    }
   ]
  },
  {
   "title": "Trottling per backend",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adv_cache_upstream_backend_throttle_level{backend=~\"$backend\"} * 100",
     "legendFormat": "{{backend}} - trottling %"
    }
   ]
  },
  {
   "title": "Jitter limit per backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "adv_cache_upstream_backend_rate_limit_total",
     "legendFormat": "{{backend}} - jitter limit"
    }
   ]
  },
  {
   "title": "Backend Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (backend) (\n      1 * adv_cache_upstream_backend_is_healthy{backend=~\".*\"}\n    + 2 * adv_cache_upstream_backend_is_sick{backend=~\".*\"}\n    + 3 * adv_cache_upstream_backend_is_dead{backend=~\".*\"}\n    + 4 * adv_cache_upstream_backend_is_buried{backend=~\".*\"}\n  )\n)\n+ on (backend)\n(\n  (\n    sum by (backend) (\n        1 * adv_cache_upstream_backend_is_healthy{backend=~\".*\"}\n      + 2 * adv_cache_upstream_backend_is_sick{backend=~\".*\"}\n      + 3 * adv_cache_upstream_backend_is_dead{backend=~\".*\"}\n      + 4 * adv_cache_upstream_backend_is_buried{backend=~\".*\"}\n    )\n  ) == bool 0\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "(\n  sum by (backend) (\n      1 * adv_cache_upstream_backend_is_healthy{backend=~\"$backend\"}\n    + 2 * adv_cache_upstream_backend_is_sick{backend=~\"$backend\"}\n    + 3 * adv_cache_upstream_backend_is_dead{backend=~\"$backend\"}\n    + 4 * adv_cache_upstream_backend_is_buried{backend=~\"$backend\"}\n  )\n)\n+ on (backend)\n(\n  (\n    sum by (backend) (\n        1 * adv_cache_upstream_backend_is_healthy{backend=~\"$backend\"}\n      + 2 * adv_cache_upstream_backend_is_sick{backend=~\"$backend\"}\n      + 3 * adv_cache_upstream_backend_is_dead{backend=~\"$backend\"}\n      + 4 * adv_cache_upstream_backend_is_buried{backend=~\"$backend\"}\n    )\n  ) == bool 0\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общее количество секунд, которые были потрачены процессом на использование процессора",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{namespace=\"$namespace\",pod=~\"$deployment.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Sum Spent Time of Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{namespace=\"$namespace\",pod=~\"$deployment.*\"}[$__rate_interval])) by(pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[ $namespace ] Application metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 }
  },
  {
   "title": "Go Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "go_threads{namespace=\"$namespace\",pod=~\"$deployment.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "[ $namespace ] Basic metrics ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Containers ready",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container) (kube_pod_container_status_ready{namespace=\"$namespace\",pod=~\"$deployment.*\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Container restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container) (increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\",pod=~\"$deployment.*\"}[$__range]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Pods count quota",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\",resource=\"pods\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\",resource=\"pods\",type=\"hard\"} * 0.8",
     "legendFormat": "threshold1"
    }
   ]
  },
  {
   "title": "Req.CPU quota",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\",resource=\"requests.cpu\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\",resource=\"requests.cpu\",type=\"hard\"} * 0.7",
     "legendFormat": "threshold1"
    }
   ]
  },
  {
   "title": "Limits CPU quota",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\",resource=\"limits.cpu\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\",resource=\"limits.cpu\",type=\"hard\"} * 0.7",
     "legendFormat": "threshold1"
    }
   ]
  },
  {
   "title": "Req.RAM quota (GiB)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\",resource=\"requests.memory\"} / 1024 / 1024 / 1024",
     "legendFormat": "usage"
    },
    {
     "expr": "(kube_resourcequota{namespace=\"$namespace\",resource=\"requests.memory\",type=\"hard\"} * 0.8 ) / 1024 / 1024 / 1024",
     "legendFormat": "threshold1"
    }
   ]
  },
  {
   "title": "Limits RAM quota (GiB)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\",resource=\"limits.memory\"} / 1024 / 1024 / 1024",
     "legendFormat": "usage"
    },
    {
     "expr": "(kube_resourcequota{namespace=\"$namespace\",resource=\"limits.memory\",type=\"hard\"} * 0.8 ) / 1024 / 1024 / 1024",
     "legendFormat": "threshold1"
    }
   ]
  },
  {
   "title": "Req. storage quota (GiB)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\",resource=\"requests.storage\"} / 1024 / 1024 / 1024",
     "legendFormat": "usage"
    },
    {
     "expr": "(kube_resourcequota{namespace=\"$namespace\",resource=\"requests.storage\",type=\"hard\"} * 0.8 ) / 1024 / 1024 / 1024",
     "legendFormat": "threshold1"
    }
   ]
  },
  {
   "title": "Containers waiting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container) (kube_pod_container_status_waiting{namespace=\"$namespace\",pod=~\"$deployment.*\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPU (real)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"$container\",pod=~\"$deployment.*\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-{{container}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\",container=\"$container\",pod=~\"$deployment.*\",resource=\"cpu\"}",
     "legendFormat": "{{pod}}-{{container}}-limit"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$namespace\",container=\"$container\",pod=~\"$deployment.*\"}",
     "legendFormat": "{{container}}:{{pod}}"
    },
    {
     "expr": "container_spec_memory_limit_bytes{namespace=\"$namespace\",container=\"$container\",pod=~\"$deployment.*\"}",
     "legendFormat": "OOM:{{container}}:{{pod}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"$deployment.*\"}[$__rate_interval])",
     "legendFormat": "{{pod}} - RX"
    },
    {
     "expr": "- irate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"$deployment.*\"}[$__rate_interval])",
     "legendFormat": "{{pod}} - TX"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "container_processes{namespace=\"$namespace\",container=\"$container\",pod=~\"$deployment.*\"}",
     "legendFormat": "{{pod}}-{{container}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 82 },
   "targets": [
    {
     "expr": "container_threads{namespace=\"$namespace\",container=\"$container\",pod=~\"$deployment.*\"}",
     "legendFormat": "{{pod}}-{{container}}"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 82 },
   "targets": [
    {
     "expr": "container_file_descriptors{namespace=\"$namespace\",container=\"$container\",pod=~\"$deployment.*\"}",
     "legendFormat": "{{pod}}-{{container}}"
    }
   ]
  },
  {
   "title": "CPU throttling",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\",container=\"$container\",pod=~\"$pod\"}[$__rate_interval]) > 0) by (pod, container) /sum(increase(container_cpu_cfs_periods_total{namespace=\"$namespace\",container=\"$container\",pod=~\"$pod\"}[$__rate_interval]) > 0) by (pod, container) ",
     "legendFormat": "{{pod}}-{{container}}"
    }
   ]
  },
  { "title": "[ $namespace ] Go Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Off-Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{namespace=\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "mspan_inuse-{{pod}}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{namespace=\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "mspan_sys-{{pod}}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{namespace=\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "mcache_inuse-{{pod}}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{namespace=\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "mcache_sys-{{pod}}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{namespace=\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "buck_hash_sys-{{pod}}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{namespace=\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "gc_sys_{{pod}}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{namespace=\"$namespace\", deployment=~\"$deployment\"} - go_memstats_other_sys_bytes{namespace=\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "other_sys_{{pod}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{namespace=\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "next_gc_{{pod}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{namespace=\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "alloc-{{pod}}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{namespace=\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "sys-{{pod}}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{namespace=\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "idle-{{pod}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "inuse-{{pod}}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{namespace=\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "released-{{pod}}"
    }
   ]
  },
  {
   "title": "Stack Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "inuse-{{pod}}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{namespace=\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "sys-{{pod}}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{namespace=\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{namespace=\"$namespace\", deployment=~\"$deployment\"} - go_memstats_frees_total{namespace=\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "timeseries",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{namespace=\"$namespace\", deployment=~\"$deployment\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"$namespace\", deployment=~\"$deployment\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{namespace=\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "[ $namespace ] Ingress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success Rate (non-4|5xx responses) in $namespace",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 312 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n    sum by (ingress) (rate(nginx_ingress_controller_requests{namespace=\"$namespace\",status=~\"2..|4..|3..\",status!=\"429\"}[$__rate_interval])) \n    / \n    sum by (ingress) (rate(nginx_ingress_controller_requests{namespace=\"$namespace\"}[$__rate_interval]))\n) >=0",
       "legendFormat": "{{ingress}}"
      }
     ]
    },
    {
     "title": "Ingress requests in $namespace",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 312 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "round(sum(irate(nginx_ingress_controller_requests{namespace=\"$namespace\"}[$__rate_interval])) by (ingress), 0.001)",
       "legendFormat": "{{ingress}}"
      }
     ]
    },
    {
     "title": "Ingress timings in $namespace",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 363 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",namespace=\"$namespace\"}[$__rate_interval])) by (le, ingress)) >= 0",
       "legendFormat": "{{ingress}} - 50 pcntl"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",namespace=\"$namespace\",service=\"$deployment\"}[$__rate_interval])) by (le, ingress)) >= 0",
       "legendFormat": "{{ingress}} - 90 pcntl"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",namespace=\"$namespace\",service=\"$deployment\"}[$__rate_interval])) by (le, ingress)) >= 0",
       "legendFormat": "{{ingress}} - 95 pcntl"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",namespace=\"$namespace\",service=\"$deployment\"}[$__rate_interval])) by (le, ingress)) >= 0",
       "legendFormat": "{{ingress}} - 99 pcntl"
      }
     ]
    },
    {
     "title": "Ingress traffic in $namespace",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 363 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(irate(nginx_ingress_controller_request_size_sum{ingress!=\"\",namespace=\"$namespace\"}[$__rate_interval])) by (ingress)",
       "legendFormat": "{{ingress}} - RX"
      },
      {
       "expr": "- sum(irate(nginx_ingress_controller_response_size_sum{ingress!=\"\",namespace=\"$namespace\",service=\"$deployment\"}[$__rate_interval])) by (ingress)",
       "legendFormat": "{{ingress}} - TX"
      }
     ]
    }
   ]
  }
 ]
}